"""Initial migration

Revision ID: 425efc8b8c61
Revises: 
Create Date: 2025-02-16 20:16:56.568372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '425efc8b8c61'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('berita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(), nullable=False),
    sa.Column('sumber', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.Column('isi', sa.Text(), nullable=False),
    sa.Column('sentimen', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_berita_id'), 'berita', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_berita_id'), table_name='berita')
    op.drop_table('berita')
    # ### end Alembic commands ###
